services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
    ports:
      - 3050:80
  client:
    build:
      context: ./client

  api:
    depends_on:
      - go_db
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /server/cmd
      - ./server:/server
    ports:
      - 8080:8080

  go_db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  redis_db:
    image: redis

  worker:
    build:
      context: ./worker
      dockerfile: ./Dockerfile
    volumes:
      - /worker/cmd
      - ./worker:/worker

volumes:
  data: {}
