services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - 3000:80
  client:
    build:
      context: ./client

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /server/cmd
      - ./server:/server
    ports:
      - 8080:8080

  worker:
    build:
      context: ./worker
      dockerfile: ./Dockerfile
    volumes:
      - /worker/cmd
      - ./worker:/worker
